version: '2'
services:
  openpnp:
    build: ./openpnp
    privileged: true
    restart: always
    network_mode: "host"
    labels:
      io.balena.features.kernel-modules: '1'
volumes:
  - ./config:/root/.openpnp2
